export function buildDocumentConfig(type, payload = {}) {
  switch (type) {
    case 'invoice': {
      const order = payload.order || null;
      const formatCurrency = payload.formatCurrency || ((value) => String(value ?? '0'));
      const rows = (order?.OrderItems || []).map((item) => ({
        item: item.title || 'Item',
        type: item.itemType || '-',
        qty: Number(item.quantity || 1),
        price: formatCurrency(item.price || 0),
        amount: formatCurrency(Number(item.price || 0) * Number(item.quantity || 1)),
      }));

      return {
        title: 'INVOICE',
        generatedAt: order?.createdAt,
        headerClassName: 'grid grid-cols-[1.2fr_auto_1fr] items-start border-b border-slate-200 pb-4',
        logoClassName: 'h-16 w-16 rounded object-contain',
        metadata: [
          { label: 'Invoice No', value: order?.id || '-' },
          { label: 'Order Status', value: order?.status || '-' },
          { label: 'Customer', value: order?.customerName || '-' },
          { label: 'Customer Email', value: order?.customerEmail || '-' },
          { label: 'Customer Phone', value: order?.customerPhone || '-' },
          { label: 'Order Type', value: order?.orderType || '-' },
          { label: 'Total Amount', value: formatCurrency(order?.totalAmount || 0) },
          {
            label: 'Delivery',
            value: order?.deliveryAddress
              ? `${order.deliveryAddress.addressLine1 || ''}, ${order.deliveryAddress.city || ''}`
              : 'Digital delivery',
          },
        ],
        columns: [
          { key: 'item', label: 'Item' },
          { key: 'type', label: 'Type' },
          { key: 'qty', label: 'Qty', align: 'right' },
          { key: 'price', label: 'Price', align: 'right' },
          { key: 'amount', label: 'Amount', align: 'right' },
        ],
        rows,
        footerNote: 'This is system generated invoice.',
      };
    }

    case 'result-report': {
      const items = Array.isArray(payload.items) ? payload.items : [];
      return {
        title: 'RESULT REPORT',
        headerClassName: 'grid grid-cols-[1.2fr_auto_1fr] items-start border-b border-slate-200 pb-4',
        logoClassName: 'h-12 w-12 rounded object-contain',
        metadata: [
          { label: 'Total Records', value: items.length },
          { label: 'Generated By', value: 'Admin Panel' },
        ],
        columns: [
          { key: 'student', label: 'Student' },
          { key: 'exam', label: 'Exam' },
          { key: 'achievement', label: 'Achievement' },
          { key: 'rank', label: 'Rank' },
          { key: 'status', label: 'Status' },
        ],
        rows: items.map((item) => ({
          student: item.displayName || '-',
          exam: item.examName || '-',
          achievement: item.achievementTitle || '-',
          rank: item.rank || '-',
          status: item.isActive ? 'Active' : 'Hidden',
        })),
        footerNote: 'This is system generated result report.',
      };
    }

    case 'student-report': {
      const items = Array.isArray(payload.items) ? payload.items : [];
      return {
        title: 'STUDENT LIST',
        headerClassName: 'grid grid-cols-[1.2fr_auto_1fr] items-start border-b border-slate-200 pb-4',
        logoClassName: 'h-12 w-12 rounded object-contain',
        metadata: [
          { label: 'Total Students', value: items.length },
          { label: 'Generated By', value: 'Admin Panel' },
        ],
        columns: [
          { key: 'name', label: 'Student Name' },
          { key: 'phone', label: 'Phone' },
          { key: 'course', label: 'Course' },
          { key: 'batch', label: 'Batch' },
          { key: 'feeStatus', label: 'Fee Status' },
        ],
        rows: items.map((student) => ({
          name: student.name || '-',
          phone: student.phone || '-',
          course: student.Course?.title || student.courseId || '-',
          batch: student.Batch?.schedule || student.batchId || '-',
          feeStatus: student.feeStatus || '-',
        })),
        footerNote: 'This is system generated student report.',
      };
    }

    case 'inventory-report': {
      const items = Array.isArray(payload.items) ? payload.items : [];
      const formatCurrency = payload.formatCurrency || ((value) => String(value ?? '0'));
      return {
        title: 'BOOK INVENTORY',
        headerClassName: 'grid grid-cols-[1.2fr_auto_1fr] items-start border-b border-slate-200 pb-4',
        logoClassName: 'h-12 w-12 rounded object-contain',
        metadata: [
          { label: 'Total Products', value: items.length },
          { label: 'Generated By', value: 'Admin Panel' },
        ],
        columns: [
          { key: 'name', label: 'Product' },
          { key: 'sku', label: 'SKU' },
          { key: 'price', label: 'Price', align: 'right' },
          { key: 'stock', label: 'Stock', align: 'right' },
          { key: 'status', label: 'Status' },
        ],
        rows: items.map((product) => ({
          name: product.name || '-',
          sku: product.sku || '-',
          price: formatCurrency(product.price || 0),
          stock: Number(product.stock || 0),
          status: product.isActive ? 'Active' : 'Inactive',
        })),
        footerNote: 'This is system generated inventory report.',
      };
    }

    case 'notice-report': {
      const items = Array.isArray(payload.items) ? payload.items : [];
      const formatDate = payload.formatDate || ((value) => String(value || '-'));
      return {
        title: 'NOTICE REPORT',
        headerClassName: 'grid grid-cols-[1.2fr_auto_1fr] items-start border-b border-slate-200 pb-4',
        logoClassName: 'h-12 w-12 rounded object-contain',
        metadata: [
          { label: 'Total Notices', value: items.length },
          { label: 'Generated By', value: 'Admin Panel' },
        ],
        columns: [
          { key: 'title', label: 'Title' },
          { key: 'type', label: 'Type' },
          { key: 'date', label: 'Date' },
          { key: 'status', label: 'Status' },
        ],
        rows: items.map((notice) => ({
          title: notice.title || '-',
          type: notice.type || '-',
          date: formatDate(notice.date),
          status: notice.isActive ? 'Visible' : 'Hidden',
        })),
        footerNote: 'This is system generated notice report.',
      };
    }

    default:
      return {
        title: 'DOCUMENT',
        headerClassName: 'grid grid-cols-[1.2fr_auto_1fr] items-start border-b border-slate-200 pb-4',
        logoClassName: 'h-12 w-12 rounded object-contain',
        metadata: [],
        columns: [],
        rows: [],
        footerNote: 'This is system generated document.',
      };
  }
}
